os: linux
language: python
jobs:
  include:
    - python: '3.5'     # test against oldest supported target
      dist: xenial
    - python: '3.8'     # test against next supported target
      dist: bionic
    - language: shell   # linux release (assumed to be oldest LTS Ubuntu)
      env:
        BUILD_CLI: true
        BUILD_SDIST: true
        BUILD_WHEEL: true
        DEPLOY_PYPI: true
        DEPLOY_RELEASES: true
      addons: {apt: {packages: [python3-venv]}}
    - os: osx           # macOS release
      language: shell
      env:
        PYENV_VERSION: 3.7
        BUILD_CLI: true
        # BUILD_GUI: true # requires `brew install tcl-tk` most likely
        DEPLOY_RELEASES: true
  allow_failures:
    - os: osx

env:
  global:
    APPIMAGHE_CACHE: "~/.cache/appimage"
    PIP_CACHE_DIR: "~/.cache/pip"
    PYENV_ROOT: "~/.pyenv-roman"
    PYENV_USE_GIT: true
    USE_VIRTUALENV: true
cache:
  directories:
    - "$HOME/.cache/appimage"
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv-roman"

install: ".travis/install.sh"
script:
  - ".travis/build_and_test.sh"
  - ".travis/build_releases.sh"
  - ".travis/dir_info.sh"
deploy:
- provider: releases
  prerelease: true # TODO: after release v1, remove this line
  token:
    secure: "lJiFCmSqmI2pSkMa/H484k7Mp6oFAtfjbqk31TghrNermjnU9cUxHAHW2xt0Kv9JREk17eymKL+D52pa2rcMmsTaTPgKtFyHm1MKFgrCifu6a3fKmDRUjAfZ2xUTlmkiyaFJkqDsCA8BQJkWmMngbtr4xFQEswltx0D3TWq3YdQenu58LFD2uci5NqjM+FASAD4aT+0D6ygzrx2QrK0el9kZKceiojRCc89U8nHkFcngtQFsMWzH0YSPqz7QF2rFqtIwkFgYQMIdpqkP1IZC1Z9uzRt3DiADA5oIMQk3puVRsEmdHqSjORVLp0kFNzhcvJqIZrQ6PaRp8k+xkxc9gIIgIdErYw5wI4zhcxNovBv6ofvjn3rFUNVSvyHCmgHnUKpkBOMxc8MEksBs5MIcDaZAQkoNQk2ony7Rz2aEa5rsaGEx5IYShXLGjRBOanSuXJCz6YllzmZKXmvcBUrHgV/Kh0d+YR0qYZpxnK2A/HCphwpiuJw+ZUYZjLdLVEKuchwwqNvnfg3CvwS4jja5ydmgOfEHglmhdjGQEEfANvxD2XGR26nGTFmb5jJt0+bQ2BQB09e7tuRU+BGAh2Rr7CbrRwbbgF/Ynwe/5knVHPGzximHxgcBfA8r4ru5ShDrQP3AfHoUDPlRDIxpvbjE5V4QEdcIEWWuogWEn3sJlOQ="
  on:
    repo: apluslms/roman
    tags: true
    condition: $DEPLOY_RELEASES = true
  file_glob: true
  file:
    - dist/*.tar.gz
    - dist/*.whl
    - dist/roman-*
    - dist/*.AppImage
    - dist/*.dmg
    - dist/*.zip
  skip_cleanup: true
  cleanup: false
- provider: script
  script: ".travis/pre_pypi.sh"
  on:
    repo: apluslms/roman
    tags: true
    condition: $DEPLOY_PYPI = true
  skip_cleanup: true
  cleanup: false
- provider: pypi
  username: __token__
  password:
    secure: "Cn3uE77wwmcnE/xapPRgIUmXuYVzH4mPQHeIo4hc5q1U8qFESfAGF6LCUVHq/2jpdVgVZt9ONcUMa7BSYKjD/NBYHxcmTUxFeOGQRisLCTtbk66UkyPI0iU/8HNdofWHsQZhEaivGsJJdY2p+bBfJ3BGdYJRhA3k69KOjJHggbXyqmQk4syHqzanpHsL1I+D3IjtxvoJYSL6tMcWLdiGPdvx2IYoba8o1JFXrl5Gc9cOeP9jcIZ1csMO51if0H+jzcpyvui89alrsivL8mpYhQBwba250kKsXEs9Owt3FVEVDbvSLuNZfoBi1HCNi6yCSO2U6qppQqwc4oFp2yX9FGvYftPn9+NHiri5byQ9sfAlnUsffV+ruywUvkyWnixcVWXD0jOz8XmPNIVlCuKsAnMwwuevH5Gs9zJNYqtW5NslJAPVQXw2RDuX1kHzYuQQtPXNaSFPF8dDf5u+5Rb+JAQLJTodjLLuN1MoB+4YSZ0dkQI2mzslCn440NzzZObNRVM+XRd0MjwL04MktzAtepNYVrEaDQB6uO5C8bHBJUv5Cv5zpxxE+prB9Ct06fI3hhqfMN83B+THSdbF1YVQtfbe8cL58SsHQdAsTuTZv0CUec5QV4bvH5Acr8ibAzz+5XGh05+2pPRWnChMzVAdfWLNs/cU+wAXuD70eSOMVaY="
  distributions: check # before_deploy builds *.whl and *.tar.gz files
  skip_existing: true
  skip_upload_docs: true
  upload_docs: false
  on:
    repo: apluslms/roman
    tags: true
    condition: $DEPLOY_PYPI = true
  skip_cleanup: true
  cleanup: false
after_deploy: ".travis/dir_info.sh"
