$schema: "http://json-schema.org/draft-07/schema"

properties:
  environment:
    title: build environment
    description: variables for build environment
    type: array
    items: 
      type: object
      minProperties: 1
      maxProperties: 1
      propertyNames:
        pattern: "^[A-Za-z_][A-Za-z0-9_]*$"
